config/routes.rb
Rails.application.routes.draw do
  root to:'static_pages#landing'

  # Devise routes
  devise_for :users
  devise_scope :user do
    # Fix problem of sign out button devise
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # Active admin
  ActiveAdmin.routes(self)
  devise_for :admin_users, {class_name: 'User'}.merge(ActiveAdmin::Devise.config)

  # priciple controller for model
  resources :users, only: [:show]
  resources :feedbacks, except: [:destroy]
  resources :notifications, only: [:index, :create, :update, :destroy]
  resources :appointments
  resources :companies, only: [:new, :create, :edit, :update]
  
  # Custom urls user
  resources :accounts, only: [:index, :create]
  resources :request_companies, only: [:index, :create]
  resources :request_users, only: [:show]
  resources :spotifies, only: [:index]
  resources :company_users, only: [:new, :create]
  resources :notification_accounts, only: [:update, :destroy]
  resources :users do
    resources :user_feedbacks, only: [:index]
  end

  
  # Static page
  get '/contact', to: 'static_pages#contact',as: 'contact'
  get '/about', to: 'static_pages#about',as: 'about'
  get '/careers', to: 'static_pages#careers',as: 'careers'
  get '/legalnotice', to: 'static_pages#legal_notice',as: 'legal_notice'
  get '/privacypolicy', to: 'static_pages#privacy_policy',as: 'privacy_policy'
  get '/landing_employees', to: 'static_pages#landing_employees',as: 'landing_employees'
  

end

app/controllers/spotifies_controller.rb
class SpotifiesController < ApplicationController
  before_action :authenticate_user!
  def index
    if params[:artist] && params[:artist] != "" && !params[:artist].nil?
      RSpotify.authenticate(ENV['SPOTI_CLIENT_ID'], ENV['SPOTI_API_SECRET'])
      if !RSpotify::Artist.search(params[:artist]).first
        flash[:error] = "Mince il semble que cet artiste n'existe pas :/"
      else 
        @artist = RSpotify::Artist.search(params[:artist]).first
        @album = @artist.albums.sample
        @tracks = @album.tracks
        @track = @tracks.sample
        @uri = @album.external_urls['spotify']
      end
    end
  end

end

app/helpers/spotifies_helper.rb
module SpotifiesHelper
end

app/views/spotifies/index.html.erb
<body>
  <br />
  <br />
  <div class="d-sm-flex align-items-center justify-content-between">
    <div class="container col-md-6">
      <div class="">
        <img class="img-fluid" src="<%=asset_path("spotify/pexels-vova-krasilnikov-2796145.jpg")%>"
          style="height:100vh;" alt="Music-related image">
      </div>
    </div>
    <div class="container col-md-6">
      <div class="">
        <h2 class="mt-5 mb-0 text-indigo">Bienvenue sur la roulette musicale</h2>
      </div>
      <div class="wrapper">
        <div class="mt-5 row">
          <div class="">
            <p class="mb-0 text-indigo">
              Cherche un artiste et obtiens une de ses musiques au hasard
            </p>
          </div>
        </div>
        <div class="mt-5 row">
           <%= form_tag(spotifies_path, method: "get") do %>
                <%= label_tag(:artist, "Quel artiste veux-tu écouter ?") %>
                <%= text_field_tag(:artist)%>
                <%= submit_tag("Search") %>
                <% end %>
        </div>
      </div>
      <div class="wrapper">
        <div class="row">
         <%if @artist != nil%>
                <p>Voila ce qu'on t'a trouvé :
                <p>
                <ul>
                    <li>Artiste : <%=@artist.name%></li>
                    <li>Album : <%=@album.name%></li>
                    <li>
                        <p>Tu peux écouter ce titre sur Spotify :</p>
                        <a href=<%=@uri%> target="_blank"><%=@track.name%></a>
                    </li>
                </ul>
                <%end%>
        </div>
      </div>
    </div>
  
</body>