config/routes.rb
Rails.application.routes.draw do
  root to:'static_pages#landing'

  # Devise routes
  devise_for :users
  devise_scope :user do
    # Fix problem of sign out button devise
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # Active admin
  ActiveAdmin.routes(self)
  devise_for :admin_users, {class_name: 'User'}.merge(ActiveAdmin::Devise.config)

  # priciple controller for model
  resources :users, only: [:show]
  resources :feedbacks, except: [:destroy]
  resources :notifications, only: [:index, :create, :update, :destroy]
  resources :appointments
  resources :companies, only: [:new, :create, :edit, :update]
  
  # Custom urls user
  resources :accounts, only: [:index, :create]
  resources :request_companies, only: [:index, :create]
  resources :request_users, only: [:show]
  resources :spotifies, only: [:index]
  resources :company_users, only: [:new, :create]
  resources :notification_accounts, only: [:update, :destroy]
  resources :users do
    resources :user_feedbacks, only: [:index]
  end

  
  # Static page
  get '/contact', to: 'static_pages#contact',as: 'contact'
  get '/about', to: 'static_pages#about',as: 'about'
  get '/careers', to: 'static_pages#careers',as: 'careers'
  get '/legalnotice', to: 'static_pages#legal_notice',as: 'legal_notice'
  get '/privacypolicy', to: 'static_pages#privacy_policy',as: 'privacy_policy'
  get '/landing_employees', to: 'static_pages#landing_employees',as: 'landing_employees'
  

end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :activity
  belongs_to :user
  belongs_to :feedback, optional: true

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  before_action :must_be_admin
  before_action :set_notification, only: [:show, :edit, :update, :destroy]
  def index
    @notifications = Notification.joins(:user).where(users: {company_id: current_user.company_id}).order(:created_at).reverse
  end
  
  def update
    if params[:is_read]
      @notification.update(is_read: true)
      respond_to do |format|
        format.html{}
        format.js{}
      end
    end

  end

  def destroy
    @notification.destroy
    respond_to do |format|
      format.html {
        redirect_to notifications_path
      }
      format.json{head :not_content}
      format.js{}
    end
  end

  private
  def set_notification
    @notification = Notification.find(params[:id])
  end
  def must_be_admin
    if !current_user.is_company_admin
      flash[:error] = "Vous n'avez pas de droit pour accéder à cette page."
      return redirect_back(fallback_location: user_path(current_user.id) )
    end
  end
  def is_super_admin?
    return current_user.is_site_admin
  end

 
end

app/views/notifications/_notification_menu.html.erb
<ul id="notification-menu" class="dropdown-menu--cus notification-menu">
        <div class="dropdown-menu-header">
          <span class="">
            Notifications
          </span>
        </div>
        <div class="dropdown-menu-content overlay-scrollbar scrollbar-hover">
            <% @notifications = all_notifications_limit %>
                  <% @notifications.each do  |noti|%>
        
                      <% if noti.activity.name == "feedback_created"%>
                        <li class="dropdown-menu-item  <%= is_read_class(noti)%>">
                          <a href="<%= feedback_path(noti.feedback_id, notification: noti, is_read: true)%>" class="dropdown-menu-link">
                          <div><i class="fas fa-gift"></i></div>
                          <span class="pt-2">
                            <%= noti.user.full_name %> vient de créer un feedback.
                            <br>
                            <span>
                              <%= get_date(noti.created_at)%>
                            </span>
                          </span>
                          </a>
                        </li>
                        
                      <% elsif noti.activity.name =="feedback_updated"%>
                         <li class="dropdown-menu-item  <%= is_read_class(noti)%>">
                          <a href="<%= feedback_path(noti.feedback_id, notification: noti, is_read: true)%>" class="dropdown-menu-link">
                          <div><i class="fas fa-comment-dots"></i></div>
                          <span class="pt-2">
                            <%= noti.user.full_name %> vient de modifier son feedback.
                            <br>
                            <span>
                              <%= get_date(noti.created_at)%>
                            </span>
                          </span>
                          </a>
                           </li>
                      <% elsif noti.activity.name =="user_created"%>
                           <li class="dropdown-menu-item  <%= is_read_class(noti)%>">
                        <a href="<%= request_user_path(noti.user, notification: noti, is_read: true)%>" class="dropdown-menu-link">
                        <div><i class="fas fa-user-plus"></i></div>
                          <span>
                            <%= noti.user.full_name %> souhaite rejoindre votre entreprise.
                            <br>
                            <span>
                              <%= get_date(noti.created_at)%>
                            </span>
                          </span>
                          </a>
                           </li>
                      <% else %>
                        <li class="dropdown-menu-item <%= is_read_class(noti)%>">
                        <a  class="dropdown-menu-link">
                        <div><i class="fas fa-info"></i></div>
                          <span class="pt-2">
                            Vous avez un nouvelle notification.
                            <br>
                            <span>
                              <%= get_date(noti.created_at)%>
                            </span>
                          </span>
                          </a>
                           </li>
                      <% end %>
                  <%end%>
        </div>
        <div class="dropdown-menu-footer" >
          <a class="dropdown-menu-link text-indigo" href="<%= notifications_path %>">
              Consulter toutes les notifications
          </a>
        </div>
</ul>

app/views/notifications/destroy.js.erb
function destroyNotification(){
  const notification = document.getElementById("notification_<%= @notification.id %>")
  notification.parentNode.removeChild(notification)
}

destroyNotification()

app/views/notifications/index.html.erb
<div class="container-fluid notifications-section">
 
  <div class ="row">
    <div class="col-12 col-md-6 mx-auto">
     <h4 class="mb-4 mt-3">Nouveaux feedbacks</h4>
      <div class="list-group feedback-noti-wrapper">
        <% @notifications.each do |notification| %>
          <% if notification.activity.name == "feedback_created"%>
              <div class="row" id="notification_<%= notification.id%>">
                  <div class="col-10">
                      <a class="list-group-item list-group-item-action" href="<%= feedback_path(notification.feedback_id, notification: notification, is_read: true)%> ">
                        <div class="row">
                            <div class="col-9 d-flex">
                               <h5 class="text-primary text-center mr-3"><i class="fas fa-gift"></i></h5>
                                <p id="noti_text_<%= notification.id %>" class="text-indigo-bold text-left <%= is_read_class(notification)%>"><%= notification.user.full_name %> vient de créer un feedback.</p>
                            </div>
                          <small class="col-3 text-beige text-right">Le <%= get_date(notification.created_at)%></small>
                        </div>
                      </a>
                  </div>
                  <div class="col-2 d-flex">
                   <a href="<%= notification_path(notification, is_read: true)%>" data-toggle="tooltip" data-placement="left" title="Marquer comme lu"
                     data-method="put" data-remote="true"
                    > <i id="icon_check_read_<%= notification.id %>" class="fas fa-check-double text-center fa-lg mt-3 mr-2 <%= is_read_disabled_class(notification)%>"></i>
                    </a>
                   <br/>
                    <a href="<%= notification_path(notification)%>" data-toggle="tooltip" data-placement="left" title="Archiver cette notification"
                     data-method="delete" data-remote="true"
                    ><i class="fas fa-archive text-center text-danger fa-lg mt-3" ></i>
                    </a>
                  </div>
            </div>
          
          <% elsif notification.activity.name =="feedback_updated"%>
            <div class="row" id="notification_<%=notification.id%>">
                  <div class="col-10">
                      <a class="list-group-item list-group-item-action" href="<%= feedback_path(notification.feedback_id, notification: notification, is_read: true)%>">
                        <div class="row">
                            <div class="col-9 d-flex">
                               <h5 class="text-primary text-center mr-3"><i class="fas fa-gift"></i></h5>
                                <p id="noti_text_<%= notification.id %>" class="text-indigo-bold text-left<%= is_read_class(notification)%>"><%= notification.user.full_name %> vient de modifier son feedback.</p>
                            </div>
                          <small class="col-3 text-beige text-right">Le <%= get_date(notification.created_at)%></small>
                        </div>
                      </a>
                  </div>
                  <div class="col-2 d-flex">
                    <a href="<%= notification_path(notification, is_read: true)%>" data-toggle="tooltip" data-placement="left" title="Marquer comme lu"
                      data-method="put" data-remote="true"
                      > <i id="icon_check_read_<%= notification.id %>" class="fas fa-check-double text-center fa-lg mt-3 mr-2 <%= is_read_disabled_class(notification)%>"></i>
                      </a>
                    <br/>
                      <a href="<%= notification_path(notification)%>" data-toggle="tooltip" data-placement="left" title="Archiver cette notification"
                      data-method="delete" data-remote="true"
                      ><i class="fas fa-archive text-center text-danger fa-lg mt-3" ></i>
                      </a>
                  </div>
            </div>
          <% end %> 
        <%end%>
      </div>
    </div>

    <div class="col-12 col-md-6 mx-auto">
      <h4 class="mb-4 mt-3">Nouveaux utilisateurs</h4>
      <div class="list-group user-noti-wrapper">
        <% @notifications.each do |notification| %>
          <% if notification.activity.name =="user_created"%>
            <div class="row" id="notification_<%= notification.id%>">
              <div class="col-10">
                  <a class="list-group-item list-group-item-action" href="<%= request_user_path(notification.user, notification: notification, is_read: true)%>">
                    <div class="row">
                        <div class="col-9 d-flex">
                          <h5 class="text-primary text-center mr-3"><i class="fas fa-user-plus"></i></h5>
                          <p id="noti_text_<%= notification.id %>" class="text-indigo-bold text-left <%= is_read_class(notification)%>"><%= notification.user.full_name %> souhaite rejoindre votre entreprise.</p>
                        </div>
                      <small class="col-3 text-beige text-right">Le <%= get_date(notification.created_at)%></small>
                    </div>
                  </a>
              </div>
              <div class="col-2 d-flex">
                <a href="<%= notification_account_path(notification.user, notification: notification)%>" data-toggle="tooltip" data-placement="left" title="Accepter ce compte"
                     data-method="patch" data-remote="true"
                    > <i class="fas fa-user-check text-center text-success fa-lg mt-3 mr-2"></i>
                    </a>
                   <br/>
                    <a href="<%= notification_account_path(notification.user, notification: notification)%>" data-toggle="tooltip" data-placement="left" title="Refuser ce compte"
                     data-method="delete" data-remote="true" data-confirm="Etes-vous sûr de refuser ce compte?"
                    ><i class="fas fa-user-times text-center text-danger fa-lg mt-3"></i>
                    </a>
              </div>
            </div>
          <%end %> 
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/notifications/update.js.erb
function updateNotification(){
  const notiElement = document.getElementById("noti_text_<%= @notification.id%>")
  const checkReadElement = document.getElementById("icon_check_read_<%= @notification.id %>")
  notiElement.classList.add("is-read")
  checkReadElement.classList.add("disable-read")
  checkReadElement.classList.remove("text-success")

}

updateNotification()

$("#flash").html('<%= j render partial: "shared/notice_banner" %>');