config/routes.rb
Rails.application.routes.draw do
  root to:'static_pages#landing'

  # Devise routes
  devise_for :users
  devise_scope :user do
    # Fix problem of sign out button devise
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # Active admin
  ActiveAdmin.routes(self)
  devise_for :admin_users, {class_name: 'User'}.merge(ActiveAdmin::Devise.config)

  # priciple controller for model
  resources :users, only: [:show]
  resources :feedbacks, except: [:destroy]
  resources :notifications, only: [:index, :create, :update, :destroy]
  resources :appointments
  resources :companies, only: [:new, :create, :edit, :update]
  
  # Custom urls user
  resources :accounts, only: [:index, :create]
  resources :request_companies, only: [:index, :create]
  resources :request_users, only: [:show]
  resources :spotifies, only: [:index]
  resources :company_users, only: [:new, :create]
  resources :notification_accounts, only: [:update, :destroy]
  resources :users do
    resources :user_feedbacks, only: [:index]
  end

  
  # Static page
  get '/contact', to: 'static_pages#contact',as: 'contact'
  get '/about', to: 'static_pages#about',as: 'about'
  get '/careers', to: 'static_pages#careers',as: 'careers'
  get '/legalnotice', to: 'static_pages#legal_notice',as: 'legal_notice'
  get '/privacypolicy', to: 'static_pages#privacy_policy',as: 'privacy_policy'
  get '/landing_employees', to: 'static_pages#landing_employees',as: 'landing_employees'
  

end

app/controllers/company_users_controller.rb
class CompanyUsersController < ApplicationController

  # GET /company_users/new
  def new
    @user = User.new
  end 

  #POST /company_users
  def create 
    @user = User.new(
      email: params[:email],
      password: params[:password], 
      password_confirmation: params[:password_confirmation],
      is_validated: true,
      is_company_admin: true,
      confirmed_at: Time.now
      )
    
    if @user.save
      redirect_to new_company_path
    else
      @user.errors.full_messages.each do |message|
        flash[:error] = message
      end
      render :company_user_new
    end  
  end 

end

app/helpers/company_users_helper.rb
module CompanyUsersHelper
end

app/views/company_users/new.html.erb
<!DOCTYPE html>
<html>

<head>
    <% content_for :title, "Entreprise | " %>
</head>

<body>
    <div class="container devise-page">
        <div class="row">
            <div class="col-md-10 col-lg-8 offset-md-3 mx-auto">
                <br><br>
                <%= form_for(@user, url: company_users_path, method: :post, local:true) do |f| %>
                <h3 class="mb-4 font-weight-normal text-center text-indigo">Essayer Feedward</h3>

                <div class="form-group mb-2">
                    <label>Renseigner votre email</label><br>
                    <%= email_field_tag :email,"", class: "form-control" %>
                </div>

                <div class="form-row mb-4">
                    <div class="col">
                        <label>Renseigner votre mot de passe</label><br>
                        <%= password_field_tag :password, "", class: "form-control" %>
                    </div>
                    <div class="col">
                        <label>Confirmer votre mot de passe</label><br>
                        <%= password_field_tag :password_confirmation, "", class: "form-control" %>
                    </div>
                </div>

                <div class="form-group mt-5">
                    <%= f.submit "Suivant", class: "btn btn-lg btn-primary btn-block" %>
                </div>
                <% end %>

                <br>

            </div>

        </div>
    </div>
</body>

</html>